/smart_radar:
  ros__parameters:
    adapters:
      adapter_0:
        hw_dev_id: 2
        hw_iface_name: can0
        hw_type: can
        port: 55555
    master_data_serial_type: can_based
    master_inst_serial_type: can_based
    sensors:
      # As many as 10 sensors all named as "sensor_<number>" in increasing order of numbers,
      # e.g., sensor_0, sensor_1, etc. The list must start with sensor_0.
      # For sensor `model`if using :
      # can: 'umrra4_can_v1_0_1', 'umrr96_can', 'umrr11_can', 'umrr9d_can_v1_0_3', 'umrr9d_can_v1_2_2', 'umrr9f_can_v2_1_1', 'umrr9f_can_v2_2_1'
      # port: 'umrra4_v1_0_1', 'umrr96', 'umrr11', 'umrr9d_v1_0_3', 'umrr9d_v1_2_2', 'umrr9f_v1_1_1', 'umrr9f_v2_1_1', 'umrr9f_v2_2_1'
      sensor_0:
        link_type: "can"
        # The model of the connected sensor.
        model: "umrr96_can"
        # Adapter id to which sensor is connected
        dev_id: 2
        # The client_id of the sensor/source, must be a unique integer.
        id: 500
        # The ip address of the sensor or of the source acting as a sensor.
        #ip: "172.22.10.101"
        # The port to be used.
        port: 55555
        # The frame_id to be set to the published messages.
        frame_id: "umrr"
        # Specify the history size.
        history_size: 10
        inst_type: "can_based"
        data_type: "can_based"
        # The interface name of the sensor
        uifname: "umrr96_t153_automotive"
        # The major version of the interface
        uifmajorv: 1
        # The minor version of the interface
        uifminorv: 2
        # The pathc version of the interface
        uifpatchv: 2
